# Generated by Django 5.2.7 on 2025-11-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Cultural Interests',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='complexity',
            field=models.CharField(choices=[('simple', 'Simple instructions'), ('moderate', 'Moderate complexity'), ('advanced', 'Advanced tasks')], default='simple', help_text='Indicates how simple or complex the role instructions are.', max_length=20),
        ),
        migrations.AddField(
            model_name='role',
            name='instructions',
            field=models.JSONField(blank=True, default=list, help_text='Short instructions for volunteers to follow.'),
        ),
        migrations.AddField(
            model_name='role',
            name='required_language_level',
            field=models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], default='I', help_text='Minimum English comfort level needed for this role.', max_length=1),
        ),
        migrations.AddField(
            model_name='role',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='General tags describing the role, such as art, festival, food, safety.'),
        ),
        migrations.AddField(
            model_name='role',
            name='time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='role',
            name='cultural_themes',
            field=models.ManyToManyField(blank=True, help_text='Used for cultural recommendations (EmiExplorer).', to='signups.culturalinterest'),
        ),
    ]
