# Generated by Django 5.2.7 on 2025-11-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0002_culturalinterest_role_complexity_role_instructions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='role',
            name='cultural_themes',
            field=models.ManyToManyField(blank=True, help_text='Used for cultural recommendations.', to='signups.culturalinterest'),
        ),
        migrations.AlterField(
            model_name='role',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='General tags describing the role, such as art or festival.'),
        ),
    ]
