# Generated by Django 5.2.7 on 2025-11-21 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0003_post_alter_role_cultural_themes_alter_role_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='culturalinterest',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='role',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='role',
            name='complexity',
        ),
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
        migrations.RemoveField(
            model_name='role',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='role',
            name='required_language_level',
        ),
        migrations.RemoveField(
            model_name='role',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='role',
            name='time',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='documents',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signups.volunteer'),
        ),
        migrations.AlterField(
            model_name='culturalinterest',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='role',
            name='cultural_themes',
            field=models.ManyToManyField(blank=True, to='signups.culturalinterest'),
        ),
        migrations.AlterField(
            model_name='role',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='signed_up_at',
        ),
    ]
