# Generated by Django 5.2.7 on 2025-11-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signups", "0004_alter_culturalinterest_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="language_level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="task_complexity",
            field=models.CharField(
                choices=[
                    ("simple", "Simple"),
                    ("moderate", "Moderate"),
                    ("complex", "Complex"),
                ],
                default="simple",
                max_length=50,
            ),
        ),
    ]
