# Generated by Django 5.2.7 on 2025-11-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signups", "0005_role_language_level_role_task_complexity"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
    ]
