# Generated by Django 5.2.7 on 2025-11-22 23:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "signups",
            "0007_enrollment_completion_date_enrollment_enrolled_date_and_more",
        ),
    ]

    operations = []
