# Generated by Django 5.2.7 on 2025-11-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signups", "0008_auto_20251122_2308"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="cultural_interests",
            field=models.ManyToManyField(
                blank=True,
                related_name="interested_volunteers",
                to="signups.culturalinterest",
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="english_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=50,
            ),
        ),
    ]
