# Generated by Django 5.2.7 on 2025-11-23 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signups", "0009_volunteer_cultural_interests_volunteer_english_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coordinator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Organization or community group",
                        max_length=200,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="coordinator_profiles/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="role",
            name="coordinator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_roles",
                to="signups.coordinator",
            ),
        ),
    ]
