# Generated by Django 5.2.7 on 2025-11-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signups", "0010_coordinator_role_coordinator"),
    ]

    operations = [
        migrations.AddField(
            model_name="coordinator",
            name="password",
            field=models.CharField(default="temporary_password", max_length=128),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="password",
            field=models.CharField(default="temporary_password", max_length=128),
        ),
    ]
